### PR TITLE
SummerProjects19/Cryptopals/Karn Tiwari/

### PR DESCRIPTION
**Pull request by ghost**
Assignment 2 Done!

### CODE REVIEW

**Comment by shanthanu9** [comment]
No no, add to the existing Cryptopals directory. You have created another directory called 'Assignment 1' and added it there.

On the existing Cryptopals directory, add your files under your folder.

**Comment by shanthanu9** [comment]
Any updates?

**Comment by ghost** [comment]
Is it correct now!

**Comment by shanthanu9** [comment]
Lol, I did not mean to change the title XD. See you haven't followed the directory structure on GitHub.
 
What you have done is added a new folder called "Assignment 1" outside Cryptopals folder and added your code in the former folder. What I am asking you to do simply move your solution code to the existing Cryptopals folder. So you will have to actually move these files in your local machine and commit the changes. Then it will be reflected. What I am asking you to do has nothing to do with the title of this PR

**Pull request closed without merging**
