### PR TITLE
Assignment-1 

### PR DESCRIPTION
**Pull request by gaurivn**
Answers to assignment-1

### CODE REVIEW

**Comment by rohit-mp** [comment]
Please do not change other people's submissions and try to keep the number of commits to a minimum.

**Comment by rohit-mp** [comment]
Submit another pr which only adds your assignment.

**Comment by gaurivn** [comment]
Okay I'll do that, sorry about that

**Comment by gaurivn** [comment]
Can you please tell me how to go about doing it, something went wrong

**Comment by gaurivn** [comment]
I'm getting Ameya's folder along with mine, I had sent you a pic on
whatsapp, pleasse tell me how to proceed further

**Pull request closed without merging**
